1747906326998	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1747906328051	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1747906328051	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1747906328053	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1747906328055	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1747906329555	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1747906329555	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1747906329557	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1747906329558	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1747906329558	Sync.Service	INFO	Starting sync at 2025-05-22 15:02:09 in browser session 9LzWDoqYy_HG
1747906329558	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1747906329560	Sync.Status	INFO	Resetting Status.
1747906329560	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1747906329561	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1747906339614	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1747906339614	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1747906339614	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1747906339614	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1747906339615	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1747906339618	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
