1748000516279	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1748000559093	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1748000559093	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748000559095	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1748000559098	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748000568421	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1748000568422	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1748000568424	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748000568425	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1748000568425	Sync.Service	INFO	Starting sync at 2025-05-23 17:12:48 in browser session wt9PXLXT_ZJY
1748000568425	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748000568427	Sync.Status	INFO	Resetting Status.
1748000568427	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1748000568428	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1748000573491	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748000573491	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1748000573491	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1748000573491	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748000573491	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1748000573493	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
