1748212820644	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1748212832703	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1748212832703	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748212832704	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1748212832706	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748212832709	Sync.SyncScheduler	DEBUG	Woke from sleep.
1748212832709	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1748212832709	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1748212832710	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748212834711	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1748212834711	Sync.Service	INFO	Starting sync at 2025-05-26 04:10:34 in browser session QeVl2r7C5Suw
1748212834711	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748212834714	Sync.Status	INFO	Resetting Status.
1748212834714	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1748212834715	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1748212834717	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748212834717	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1748212834717	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1748212834717	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748212834717	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1748212834718	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
